### ISSUE TITLE
some failure

### ISSUE THREAD

**Issue by jimmywarting** [pixa-pics/SuperJSONatural#1]
this for example dose not work...
```js
fetch('https://api.github.com/repos/nodejs/node/issues/19393/comments')
  .then(res => res.json())
  .then(json => {
    var str = SuperJSONatural().pack(json)
    const val = SuperJSONatural().unpack(str)
    console.log(val)
  })
```

**Comment by vipertechofficial** [comment]
@jimmywarting We (Just as [Ariane Five](https://www.bugsnag.com/blog/bug-day-ariane-5-disaster)) didn't expected our JSON's header to be **above the number 65553** (bytes length) to which we were previously using two bytes to encode the length... I am very sorry for having not checked this issue sooner yet it should be correct now in V3.0 even if the JSON header is of an encoded bytes length greater than the entire positive number we can store within two bytes (we use 4 bytes now it should be quite enough).

Also, hopefully no spaceship were lost due to this error, but I am very glad you had had the idea to open this issue, I was also wondering why it wasn't working in some case but I was very busy on things to do aside of coding. So yeah, try again with the newest version and THANKS A LOT for your contribution, very appreciated, as we can see each bytes matters (either it can be for an issue or for something else)! 

Just tell me back your result and I will be able to close this issue somehow soon I bet.

EDIT:

---

Nobody:
-
The JSON Header:
![ariane-v501-4juin96-300x198](https://user-images.githubusercontent.com/74778466/221709613-6f1023e5-758c-48a2-805a-eb39f159bf78.jpg)
